[package]
name = "mapfold-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
num-bigint = "0.4.6"
num-traits = "0.2.19"
